export const TransactionData = [
  {
    id: 1,
    name: "Radif Ganteng",
    buktiTransfer: "bca.jpg",
    RemainingActive: 26,
    StatusUser: "Active",
    StatusPayment: "Apporve",
  },
  {
    id: 2,
    name: "Haris Rahman",
    buktiTransfer: "bni.jpg",
    RemainingActive: 26,
    StatusUser: "Active",
    StatusPayment: "Apporve",
  },
  {
    id: 3,
    name: "Aming Subagiyo",
    buktiTransfer: "permata.jpg",
    RemainingActive: 0,
    StatusUser: "Not Active",
    StatusPayment: "Cancel",
  },
  {
    id: 4,
    name: "Haris Astina",
    buktiTransfer: "permata.jpg",
    RemainingActive: 0,
    StatusUser: "Not Active",
    StatusPayment: "Pending",
  },
  {
    id: 5,
    name: "Aziz Oni On",
    buktiTransfer: "bi.jpg",
    RemainingActive: 0,
    StatusUser: "Not Active",
    StatusPayment: "Pending",
  },
  {
    id: 6,
    name: "Sugeng No Pants",
    buktiTransfer: "bni.jpg",
    RemainingActive: 0,
    StatusUser: "Not Active",
    StatusPayment: "Pending",
  },
];
